menu:
  Blog: /
  Archive: /archives/
  # Twitter: https://twitter.com/JohnWmm/
  # GitHub: https://github.com/ifyour/
  Docs: /docs/
  About: /about/

favicon: /favicon.png
logo: /favicon.png

# Comment
# e.g disqus: ifyour
disqus:

# 是否开启 Gitment 评论系统
gitment: true

# 是否启用 Medium zoom 图片放大
zoom: true

# Analytics
# google-analytics:
ga: UA-120929321-1

# Copyright Infomation
startyear: 2015
